server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址 http://192.168.33.10:18848/
        server-addr: 192.168.33.10:18848
management:
  endpoints:
    web:
      exposure:
        include: '*'




